# Builder Stage
FROM node:18-alpine AS builder

WORKDIR /frontend-app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Production Stage 

FROM node:18-alpine AS production

WORKDIR /frontend-app

# Copy the built artifacts from the builder stage
COPY --from=builder /frontend-app/.next/standalone ./
COPY --from=builder /frontend-app/.next/static ./.next/static

# Set the environment variables (if needed)
ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "server.js"]