FROM python:3.11.4-slim-bullseye AS base

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

ENV HOME=/app
RUN mkdir $HOME
WORKDIR $HOME

RUN mkdir $HOME/public
RUN mkdir $HOME/public/static
RUN mkdir $HOME/public/media

# install system dependencies
RUN apt-get update && apt-get install -y gcc netcat

RUN pip install --upgrade pip

COPY requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY . .

ENTRYPOINT ["sh", "./entrypoint.sh"]
