# pull official base image
FROM node:14.16.0-alpine

# set working directory
WORKDIR /frontend-admin-app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /frontend-admin-app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add app
COPY . ./

# start app
CMD ["npm", "start"]